<% self.filename = 'Dockerfile' -%>
<% self.executable = false -%>
FROM <%= from %>
MAINTAINER <%= maintainer %>

RUN apt-get update -yq

ADD ./.run /docker/run

EXPOSE 80 443
VOLUME["/net", "/bridge"]

CMD["/docker/run/bridge"]
