<% self.filename = 'Dockerfile' -%>
<% self.executable = false -%>
# See http://docs.docker.io/en/latest/use/builder/ for more info
FROM <%= from %>
MAINTAINER <%= maintainer %>

RUN apt-get update -yq

ADD ./.run /docker/run

EXPOSE 80 443
VOLUME["/net", "/bridge"]

CMD["/docker/run/bridge"]
