<% self.filename = 'Dockerfile' -%>
<% self.executable = false -%>
FROM <%= from %>
MAINTAINER <%= maintainer %>

# See http://docs.docker.io/en/latest/use/builder/ for more info

RUN apt-get update -yq

ADD ./.run /docker/run

EXPOSE 22 80 443
VOLUME ["/net", "/bridge"]

CMD ["/docker/run/bridge"]
